### ISSUE TITLE
Export interfaces

### ISSUE THREAD

**Issue by pakokrew** [zeriontech/defi-sdk-js#6]
It could be great if you could export types in the main export so we can use them in our typescript codes.

I'm using this for now as a workaround:

`import { ProtocolBalanceInterface } from 'defi-sdk/dist/protocols/interfaces'`

**Comment by everdimension** [comment]
Hi! Thank you for opening the issue.

We are changing the direction of this library to be a client for Zerion API.

You can find the old code in the archived repository: https://github.com/zeriontech/defi-sdk-js-archived
It can still be installed with npm.

If you're still experiencing the issue please let us know.
I will close the issue for now.
