### ISSUE TITLE
Maker not supported

### ISSUE THREAD

**Issue by ojnc** [zeriontech/defi-sdk-js#7]
Maker seems not supported
In output of **getProtocolNames** there is "Maker Governance" but no "Maker" or "Maker Dao"

Tried this code that works for "Compound"
```
var protocol = "Maker";
defiSdk.getProtocolBalance(account, protocol).then(function (balance) {
    console.log('\n\ngetProtocolBalance "Maker"');
    console.log(JSON.stringify(balance, null, 2));
});

```
I got exception
(node:7444) UnhandledPromiseRejectionWarning: **ProtocolDoesNotExistError**: Protocol [Maker] does not exists get exception

Please provide solution or workaround

Regards
Jayanta

**Comment by everdimension** [comment]
Hi! Thank you for opening the issue.

We are changing the direction of this library to be a client for Zerion API.

You can find the old code in the archived repository: https://github.com/zeriontech/defi-sdk-js-archived
It can still be installed with npm.

If you're still experiencing the issue please let us know.
I will close the issue for now.
