### ISSUE TITLE
upgrade to v3 adapter

### ISSUE THREAD

**Issue by gasolin** [zeriontech/defi-sdk-js#8]
sometimes got error `contract not deployed (contractAddress="0x06FE76B2f432fdfEcAEf1a7d4f6C3d41B5861672", operation="getDeployed", version=4.0.48`

according https://docs.zerion.io/smart-contracts/addresses/main-contracts

the new AdapterRegistry (v3) is `0xaDfc6460233221eCa99daC25d00f98d32eA3989e`

**Comment by everdimension** [comment]
Hi! Thank you for opening the issue.

We are changing the direction of this library to be a client for Zerion API.

You can find the old code in the archived repository: https://github.com/zeriontech/defi-sdk-js-archived
It can still be installed with npm.

If you're still experiencing the issue please let us know.
I will close the issue for now.
